#version 450

#extension GL_GOOGLE_include_directive: require

#include "include/Math.iglsl"
#include "include/Mesh.iglsl"

layout(push_constant) uniform GlobalContext {
    uint indirectDrawCount;
} gs;

layout(set = 0, binding = 0) writeonly buffer Commands 
{
	VertexIndirectCommand commands[];
} cmdBuffer;

layout(set = 0, binding = 1, r32ui) uniform uimageBuffer globalDebugIndices;

layout(set = 0, binding = 2) uniform usamplerBuffer globalDebugTypes;

layout(set = 0, binding = 3) uniform CameraData {
     mat4 view;
     mat4 proj;
     Frustum f;
     mat4 world;
} cData;

layout(set = 0, binding = 4) readonly buffer DDSBuffer 
{
    DebugDrawStruct objects[];
} ddsbuffer;

layout(set = 0, binding = 5) writeonly buffer commandCounts 
{
    uint visibleCount;
    uint invisibleCount;
} cCounts;

Frustum transformFrustrum;

void CalculateFrustrum()
{
    transformFrustrum.nearplane = TransformPlane(cData.world, cData.f.nearplane);
    transformFrustrum.farplane = TransformPlane(cData.world, cData.f.farplane);
    transformFrustrum.topplane = TransformPlane(cData.world, cData.f.topplane);
    transformFrustrum.bottomplane = TransformPlane(cData.world, cData.f.bottomplane);
    transformFrustrum.rightplane = TransformPlane(cData.world, cData.f.rightplane);
    transformFrustrum.leftplane = TransformPlane(cData.world, cData.f.leftplane);
}

bool CheckAllPlanesAgainstAABB(uint index)
{
    CalculateFrustrum();
    DebugDrawStruct mainStruct = ddsbuffer.objects[index];

    vec4 minBox = ((mainStruct.center - mainStruct.halfExtents) * mainStruct.scale);

    vec4 maxBox = ((mainStruct.center + mainStruct.halfExtents) * mainStruct.scale);
    
     Frustum testFrustrum = transformFrustrum; //cData.f

    vec4 transAABBMin =   minBox;
    vec4 transAABBMax =   maxBox;

    vec4 AABBMin = min(transAABBMin, transAABBMax);
    vec4 AABBMax = max(transAABBMin, transAABBMax);

    bool check = CheckAABB(AABBMin, AABBMax, testFrustrum.nearplane.planeEquation);

    if (!check)
    {
        return false;
    }

    check = CheckAABB(AABBMin, AABBMax, testFrustrum.farplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    
    check = CheckAABB(AABBMin, AABBMax, testFrustrum.topplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    check = CheckAABB(AABBMin, AABBMax, testFrustrum.bottomplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    
    check = CheckAABB(AABBMin, AABBMax, testFrustrum.rightplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    check = CheckAABB(AABBMin, AABBMax, testFrustrum.leftplane.planeEquation);

    if (!check)
    {
        return false;
    }
    
    return true;
}

bool CheckAllPlanesAgainstSphere(uint index)
{
    CalculateFrustrum();

    DebugDrawStruct mainStruct = ddsbuffer.objects[index];

    vec4 sphere = mainStruct.center;
    
    float r = mainStruct.halfExtents.x;

    vec3 transPosition = sphere.xyz;

    Frustum testFrustrum = transformFrustrum; //cData.f

    float dist = DistanceFromPlane(testFrustrum.nearplane.planeEquation, transPosition);

    if (dist <= r)
    {
        return false;
    }

    dist = DistanceFromPlane(testFrustrum.farplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }
    
    
    dist = DistanceFromPlane(testFrustrum.topplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }
    
    dist = DistanceFromPlane(testFrustrum.bottomplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }
    
    
    dist = DistanceFromPlane(testFrustrum.rightplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }
    
    dist = DistanceFromPlane(testFrustrum.leftplane.planeEquation, transPosition);

    if (dist < -r)
    {
        return false;
    }

    return true;
    
}

bool CheckDebugDrawAgainstFrustrum(uint debugType, uint index)
{
    bool ret = false;
    
    if (debugType == DEBUG_DRAW_TYPE_BOX)
    {
       ret = CheckAllPlanesAgainstAABB(index);
    }
    else if (debugType == DEBUG_DRAW_TYPE_SPHERE)
    {
        ret = CheckAllPlanesAgainstSphere(index);
    }

    return ret;
}

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
	uint index = (gl_WorkGroupID.x * gl_WorkGroupSize.x) + gl_LocalInvocationID.x;

    if (index >= gs.indirectDrawCount)
    {
        return;
    }

    uint debugType = uint(texelFetch(globalDebugTypes, int(index)).r);

    bool visible = CheckDebugDrawAgainstFrustrum(debugType, index);

    if (!visible)
    {
        uint invisibleIndex = atomicAdd(cCounts.invisibleCount, 1u);
        cmdBuffer.commands[gs.indirectDrawCount-(1+invisibleIndex)].instanceCount = 0;
        return;
    } 

    uint visibleIndex = atomicAdd(cCounts.visibleCount, 1u);

    imageStore(globalDebugIndices, int(visibleIndex), uvec4(index, 0, 0, 0));

    if (debugType == DEBUG_DRAW_TYPE_BOX)
    {
        cmdBuffer.commands[visibleIndex].vertexCount = 24;
        cmdBuffer.commands[visibleIndex].instanceCount = 1;
        cmdBuffer.commands[visibleIndex].firstVertex = 0;
        cmdBuffer.commands[visibleIndex].firstInstance = 0;

    }
    else if (debugType == DEBUG_DRAW_TYPE_SPHERE)
    {
        vec4 temp = ddsbuffer.objects[index].halfExtents;
        uint numSlices = floatBitsToUint(temp.y);
        cmdBuffer.commands[visibleIndex].vertexCount = 2*numSlices;
        cmdBuffer.commands[visibleIndex].instanceCount = 1;
        cmdBuffer.commands[visibleIndex].firstVertex = 0;
        cmdBuffer.commands[visibleIndex].firstInstance = 0;
    }
}