#version 450

#extension GL_GOOGLE_include_directive: require

#include "include/Math.iglsl"
#include "include/Mesh.iglsl"
#include "include/Lights.iglsl"

layout(push_constant) uniform GlobalContext 
{
	uint objCount;
	uint lightCount;
} gs;

layout(set = 0, binding = 0) writeonly buffer Commands 
{
	IndexedIndirectCommand commands[];
} cmdBuffer;

layout(set = 0, binding = 1) buffer PMBuffer 
{
    MeshDetails objects[];
} perModelBuffer;

layout(set = 0, binding = 2, r32ui) uniform uimageBuffer globalSMRenderableIndices;

layout(set = 0, binding = 3) writeonly buffer commandCounts 
{
    uint visibleCount;
    uint invisibleCount;
} cCounts;

layout(set = 0, binding = 4) readonly buffer RENDBuffer
{
    MeshRenderable renderables[];
} rends;

layout(set = 0, binding = 5) readonly buffer GeomDescBuffer
{
    GeometryDetails details[];
} geomDetails;

layout(set = 0, binding = 6) readonly buffer GeomInstBuffer
{
    GeometryRenderable geomRenderables[];
} geomRends;

layout(set = 1, binding = 0) readonly buffer GLBuffer 
{
    LightSource objects[];
} lightBuffer;

layout(set = 1, binding = 1, r32ui) uniform uimageBuffer globalSMRenderableStart;
layout(set = 1, binding = 2, r32ui) uniform uimageBuffer globalSMRenderableCount;
layout(set = 1, binding = 3, r32ui) uniform uimageBuffer globalSMPerRendIndices;
layout(set = 1, binding = 4) uniform usamplerBuffer globalLightTypes;

const uint MAX_SHADOW_SAMPLES = 16u;
shared uint allocIndex;

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

void main()
{
	uint index = (gl_WorkGroupID.x * gl_WorkGroupSize.x) + gl_LocalInvocationID.x;

    if (index >= gs.objCount)  {
        return;
    }

    uint tempShadowIndices[MAX_SHADOW_SAMPLES];

    uint viewableByShadowMap = 0;

    for (uint light = 0; light<gs.lightCount; light++)
    {
        uint lType = uint(texelFetch(globalLightTypes, int(light)).r);

        if (lType == LIGHT_TYPE_DIRECTIONAL)
        {
           tempShadowIndices[viewableByShadowMap] = light;
           viewableByShadowMap += 1;
        }
        else if (lType == LIGHT_TYPE_POINT)
        {
            
        }
        else if (lType == LIGHT_TYPE_SPOT)
        {
            
        }

        if (viewableByShadowMap == MAX_SHADOW_SAMPLES)
        {
            break; 
        }
    }

    if (viewableByShadowMap == 0)
    {
        uint invisibleIndex = atomicAdd(cCounts.invisibleCount, 1u);
        cmdBuffer.commands[gs.objCount-(1+invisibleIndex)].instanceCount = 0;
        return;
    } 

    uint visibleIndex = atomicAdd(cCounts.visibleCount, 1u);
    uint smStartIndex = atomicAdd(allocIndex, viewableByShadowMap);

    imageStore(globalSMRenderableIndices, int(visibleIndex), uvec4(index, 0, 0, 0));
    imageStore(globalSMRenderableStart, int(index), uvec4(smStartIndex, 0, 0, 0));
    imageStore(globalSMRenderableCount, int(index), uvec4(viewableByShadowMap, 0, 0, 0));

    uint meshIndex = rends.renderables[index].meshIndex;
   
    cmdBuffer.commands[visibleIndex].instanceCount = viewableByShadowMap;
    cmdBuffer.commands[visibleIndex].firstIndex = perModelBuffer.objects[meshIndex].firstIndex;
    cmdBuffer.commands[visibleIndex].indexCount = perModelBuffer.objects[meshIndex].indexCount;
    cmdBuffer.commands[visibleIndex].firstInstance = 0;
    cmdBuffer.commands[visibleIndex].vertexOffset = 0;

    for (uint light = 0; light<viewableByShadowMap; light++)
    { 
        imageStore(globalSMPerRendIndices, int(smStartIndex), uvec4(tempShadowIndices[light], 0, 0, 0));
        smStartIndex += 1;   
    }

    return;
}

