#version 460

#extension GL_GOOGLE_include_directive: require
#extension GL_EXT_shader_8bit_storage : enable

#include "include/UI.iglsl"


layout(set = 0, binding = 0) readonly buffer UIContainers
{
    UIContainer renderables[];
} conts;

layout(set = 0, binding = 1) readonly buffer UIRetainedContainers
{
    UIRetainedContainer renderables[];
} retainedConts;

layout(set = 0, binding = 2) uniform usamplerBuffer UITextToContainerID;

layout(set = 0, binding = 3) readonly buffer UITextPool 
{
	uint8_t text[];
} textPool;

layout(set = 0, binding = 4) readonly buffer FontData
{
    FontDataStruct fData[];  
} fData;

layout(set = 0, binding = 5) writeonly buffer UITextVertices 
{
	UITextVertex textVerts[];
} textVertices;

layout(set = 0, binding = 6) writeonly buffer commands
{
    VkDrawIndirectCommand command[];
} comStructs;

layout(set = 0, binding = 7) readonly buffer FontWidths
{
    int fontWidths[];
} fontWidths;

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint lIndex =  gl_WorkGroupID.x;

    uint uiIndex = uint(texelFetch(UITextToContainerID, int(lIndex)).r);

    uint bitfields = conts.renderables[uiIndex].bitfields.z;

    uint textSize = GET_TEXT_SIZE(bitfields);

    uint textOffset = GET_TEXT_BUFFER_LOCATION(bitfields);

    vec2 uiSize = retainedConts.renderables[uiIndex].absoluteSize; 
  
    vec2 uiStart = retainedConts.renderables[uiIndex].anchorPoint; 

    FontDataStruct mainFontData = fData.fData[0];

    float invAspect = uiSize.y / uiSize.x;

    float textHeight = uiSize.y * (float(mainFontData.fontHeight) / float(mainFontData.cellHeight));
    
    float padleft = uiSize.x * 0.05;

    float padTop = uiSize.y - (textHeight + (uiSize.y * 0.01));
   
    vec2 textCurrPos = vec2(padleft, padTop) + uiStart;

    uint LETTERSPERROW = mainFontData.lettersPerRow;

    uint vertexStart = textOffset * 4;

    uint iter = vertexStart;

    uint fontWidthOffset = 256 * 0;

    uint i = 0;

    for (; i<textSize; i++)
    {
        uint letter = uint(textPool.text[i+textOffset]); 

        if (letter < mainFontData.startingChar)
        {
            break;
        }

        letter -= mainFontData.startingChar;

        uint tx = (letter % LETTERSPERROW);

        uint ty = (letter / LETTERSPERROW);

        int letterwidth = fontWidths.fontWidths[letter+fontWidthOffset];

        uint cx = tx * mainFontData.cellWidth;

        uint cy = ty * mainFontData.cellHeight;

        uint cx2 = cx + letterwidth;

        uint cy2 = cy + mainFontData.fontHeight;

        float s1 = float(cx) / float(mainFontData.pictureWidth);

        float t1 = float(cy) / float(mainFontData.pictureHeight);

        float s2 = float(cx2) / float(mainFontData.pictureWidth);

        float t2 = float(cy2) / float(mainFontData.pictureHeight);

        float textHorizontalStride = (uiSize.x * invAspect * (float(letterwidth)/float(mainFontData.cellWidth)));

        float left = textCurrPos.x;
        float right = textCurrPos.x + textHorizontalStride;
        float top = textCurrPos.y;
        float bottom = textCurrPos.y + textHeight;

        textVertices.textVerts[iter+0].pos = vec2(left, top);
        textVertices.textVerts[iter+0].texCoords = vec2(s1, t1);
        textVertices.textVerts[iter+1].pos = vec2(right, top);
        textVertices.textVerts[iter+1].texCoords = vec2(s2, t1);
        textVertices.textVerts[iter+2].pos = vec2(left, bottom);
        textVertices.textVerts[iter+2].texCoords = vec2(s1, t2);
        textVertices.textVerts[iter+3].pos = vec2(right, bottom);
        textVertices.textVerts[iter+3].texCoords = vec2(s2, t2);

        iter += 4;

        textCurrPos.x += textHorizontalStride;
    }

    comStructs.command[lIndex].vertexCount = i * 6; 
    comStructs.command[lIndex].firstVertex = 0; 
    comStructs.command[lIndex].instanceCount = 1;
    comStructs.command[lIndex].firstInstance = 0;

	return;
}