#version 460

#extension GL_GOOGLE_include_directive: require
#extension GL_EXT_shader_8bit_storage : enable

#include "include/UI.iglsl"

#define BITMAP_FONT_BOTTOM_ADJUSTED 2

layout(set = 0, binding = 0) readonly buffer UIContainers
{
    UIContainer renderables[];
} conts;

layout(set = 0, binding = 1) readonly buffer UIRetainedContainers
{
    UIRetainedContainer renderables[];
} retainedConts;

layout(set = 0, binding = 2) uniform usamplerBuffer UITextToContainerID;

layout(set = 0, binding = 3) readonly buffer UITextPool 
{
	uint8_t text[];
} textPool;

layout(set = 0, binding = 4) readonly buffer FontData
{
    FontDataStruct fData[];  
} fData;

layout(set = 0, binding = 5) writeonly buffer UITextVertices 
{
	UITextVertex textVerts[];
} textVertices;

layout(set = 0, binding = 6) writeonly buffer commands
{
    VkDrawIndirectCommand command[];
} comStructs;

layout(set = 0, binding = 7) readonly buffer FontWidths
{
    int fontWidths[];
} fontWidths;

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint lIndex =  gl_WorkGroupID.x;

    uint uiIndex = uint(texelFetch(UITextToContainerID, int(lIndex)).r);

    uvec2 bitfields = conts.renderables[uiIndex].bitfields.zw;

    uint textSize = GET_TEXT_SIZE(bitfields.x);

    uint textOffset = GET_TEXT_BUFFER_LOCATION(bitfields.x);

    uint fontIndex = GET_TEXT_INFO_FONT_INDEX(bitfields.y);

    float requestedFontSize = max(float(GET_TEXT_INFO_FONT_SIZE(bitfields.y)), 1.0);

    float justifiedPad = GET_TEXT_INFO_JUSTIFIED_PAD(bitfields.y);
    
    float bottomPad = GET_TEXT_INFO_BOTTOM_PAD(bitfields.y);

    vec2 uiSize = retainedConts.renderables[uiIndex].absoluteSize; 
  
    vec2 uiStart = retainedConts.renderables[uiIndex].anchorPoint; 

    FontDataStruct mainFontData = fData.fData[fontIndex];

    vec2 fontScale = vec2(requestedFontSize / float(mainFontData.cellWidth), requestedFontSize / float(mainFontData.cellHeight));

    float fontHeight = float(mainFontData.fontHeight - mainFontData.globalHeightModifier - BITMAP_FONT_BOTTOM_ADJUSTED);

    vec2 drawWidthHeight = vec2(float(mainFontData.cellWidth), float(mainFontData.cellHeight));

    vec2 fPicWidthHeight = vec2(float(mainFontData.pictureWidth), float(mainFontData.pictureHeight));

    float invAspect = uiSize.y / uiSize.x;

    float textHeight = (uiSize.y * (fontHeight / drawWidthHeight.y)) * fontScale.y;

    float textHangOver = min(uiSize.y / textHeight, 1.0);

     textHeight = min(textHeight, uiSize.y);
    
    float padJust = uiSize.x * justifiedPad;

    float padTop = max(uiSize.y - (textHeight + (uiSize.y * bottomPad)), 0.0);
   
    vec2 textCurrPos = vec2(padJust, padTop) + uiStart;

    uint iter = textOffset * 4;

    uint i = 0;

    for (; i<textSize; i++)
    {
        if (textCurrPos.x >= uiSize.x)
        {
            break;
        }

        uint letter = uint(textPool.text[i+textOffset]); 

        if (letter < mainFontData.startingChar)
        {
            break;
        }

        letter -= mainFontData.startingChar;

        uint tx = (letter % mainFontData.lettersPerRow);

        uint ty = (letter /  mainFontData.lettersPerRow);

        float letterwidth = float(fontWidths.fontWidths[letter+mainFontData.fontWidthOffset]);

        float textHorizontalStride = (uiSize.x * invAspect * ((letterwidth * fontScale.x) / drawWidthHeight.x));

        float textHangOverWidth = min((uiSize.x + uiStart.x) / (textCurrPos.x + textHorizontalStride), 1.0);

        textHorizontalStride *= textHangOverWidth;

        float left = textCurrPos.x;
        float right = textCurrPos.x + textHorizontalStride;
        float top = textCurrPos.y;
        float bottom = textCurrPos.y + textHeight;

        vec2 cxy1 = vec2(float(tx * mainFontData.cellWidth), float(ty * mainFontData.cellHeight + mainFontData.globalHeightModifier));

        vec2 cxy2 = vec2(cxy1.x + (letterwidth * textHangOverWidth), cxy1.y + (fontHeight * textHangOver));

        vec2 st1 = cxy1 / fPicWidthHeight; 

        vec2 st2 = cxy2 / fPicWidthHeight; 

        textVertices.textVerts[iter+0].pos = vec2(left, top);
        textVertices.textVerts[iter+0].texCoords = st1;
        textVertices.textVerts[iter+1].pos = vec2(right, top);
        textVertices.textVerts[iter+1].texCoords = vec2(st2.x, st1.y);
        textVertices.textVerts[iter+2].pos = vec2(left, bottom);
        textVertices.textVerts[iter+2].texCoords = vec2(st1.x, st2.y);
        textVertices.textVerts[iter+3].pos = vec2(right, bottom);
        textVertices.textVerts[iter+3].texCoords = st2;

        iter += 4;

        textCurrPos.x += textHorizontalStride;
    }

    comStructs.command[lIndex].vertexCount = i * 6; 
    comStructs.command[lIndex].firstVertex = 0; 
    comStructs.command[lIndex].instanceCount = 1;
    comStructs.command[lIndex].firstInstance = 0;

	return;
}